phrase:
  access_token: 2e7795ddc27754b089eae342c08f7a05ce3ec51de9737afda5ccba77bb33a86a
  project_id: a15e7673541734e7ed9c63a4a4dd9833
  file_format: html

  push:
    sources:
    - file: ./index_en-US.html
      params:
       locale_id: 16bfb780da6b0a435d91995091991148
        
  pull:
    targets:
    - file: ./index_<locale_code>.html
    params:
     locale_id: 0ac5fe5ed2d305c42d5c223b35607e70
      format_option:
        document_id: 3945
